version: 0.2

phases:
  pre_build:
    commands:
      - echo "Entrando a la fase pre_build"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Construimos la imagen con el puerto de la aplication
      - docker build -t $ECR_REPOSITORY_NAME:$TAG .

      # Tag la imagen docker con el puerto de la aplication 
      - docker tag $ECR_REPOSITORY_NAME:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$TAG

  build:
    commands:
      - echo "Entrando a la fase de build"
      - echo "Pushing the Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$TAG

      - echo "Pushing the Docker websocket image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$TAG

artifacts:
  files:
    - deploy/appspec.yml
    - deploy/docker-compose.yml
    - deploy/start-containers.sh
  discard-paths: yes
