version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/t-cuida-web
hooks:
  ApplicationStart:
    - location: start-containers.sh
      timeout: 300
      runas: ubuntu
